create table "SAFETY".ACCOUNTS
(
	ID BIGINT not null primary key,
	ANSWER VARCHAR(120),
	EMAIL VARCHAR(255),
	ISACTIVE SMALLINT default 0 not null,
	LAST_MODIFIED TIMESTAMP not null,
	LOGIN VARCHAR(255),
	NAME VARCHAR(255),
	PASSWORD VARCHAR(256) not null,
	PHONE VARCHAR(12),
	QUESTION VARCHAR(120),
	SURNAME VARCHAR(32) not null,
	TYPE VARCHAR(255),
	VERSION BIGINT not null,
	VERIFIEDBY BIGINT
)

create table "SAFETY".ADMINISTRATORS
(
	ID BIGINT not null primary key,
	ADMINSTAMP VARCHAR(120) not null,
	LAST_MODIFIED TIMESTAMP not null,
	VERSION BIGINT not null,
	ACCOUNT_ID BIGINT
)